header:
  version: 14

# The machine as it is written into the `local.conf` of bitbake.
machine: raspberrypi4-64

# The distro name as it is written into the `local.conf` of bitbake.
distro: poky

# The main target
target: rpilinux-image

repos:
  meta-raspberrypi:
    url: http://git.yoctoproject.org/git/meta-raspberrypi
    path: extern/
    tag: scarthgap
  poky:
    url: http://git.yoctoproject.org/git/poky
    tag: scarthgap
    path: extern/
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-openembedded:
    url: git://git.openembedded.org/meta-openembedded
    tag: scarthgap
    path: extern/
    layers:
      meta-oe:
      meta-multimedia:
      meta-networking:
      meta-python:
  local:
    path: meta-rpilinux

local_conf_header:
  ipk: |
    PACKAGE_CLASSES ?= "package_ipk"
    PATCHRESOLVE = "noop"
